name: Action Workflow

on: [push]

jobs:
    run-github-action:
        runs-on: ubuntu-latest
        steps:
            -   name: Simple javascript Action
                id: hello
                uses: actions/hello-world-javascrpit-action@v1
                with:
                    who-to-greet: hitaishi2k22
            -   name: get the output time
                run: echo "{{steps.hello.outputs.time}}"            
        
